# Generated by Django 5.0.6 on 2024-07-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_remove_attendance_timestamp_attendance_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='age',
            new_name='semester',
        ),
    ]
