# Generated by Django 5.0.6 on 2024-07-29 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0004_rename_age_people_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='semester',
            new_name='age',
        ),
    ]
